security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
server:
  port: 8081

test:
  password: ${BASIC_AUTH_PASS}
  username: ${BASIC_AUTH_USER}
  api-host: ${API_HOST}

