security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
cso:
  host: ${ORDS_HOST}
  caching: ${CACHING}
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  ttl: ${REDIS_TTL_SEC}
  redis-auth-pass: ${REDIS_AUTH_PASS}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health

