# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability Scan using Trivy Scanner

on:
  workflow_dispatch:

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-latest
    env:
      BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
      BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK build environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build an image from Dockerfile
        run: |
          docker build -t jag-role-registry .

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: jag-role-registry
          format: sarif
          output: trivy-results.sarif
          exit-code: 0
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif
